# Generated by Django 3.2.8 on 2021-10-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название самоката')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('material_ram', models.CharField(max_length=100, null=True, verbose_name='Материал рамы')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.CharField(max_length=100, null=True, verbose_name='Вес')),
                ('bearings', models.CharField(max_length=100, null=True, verbose_name='Подшибники')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/')),
                ('price', models.CharField(default='Договорнаяя', max_length=100, null=True, verbose_name='Цена (BYN)')),
                ('type_of_ram', models.BooleanField(blank=True, null=True, verbose_name='Складная рама')),
                ('slug', models.SlugField(max_length=100, null=True, verbose_name='Слаг')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Самокат',
                'verbose_name_plural': 'Самокаты',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Byke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название велосипеда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('material_ram', models.CharField(max_length=100, verbose_name='Материал рамы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transmission', models.IntegerField(verbose_name='Количество передач')),
                ('diameter_wheel', models.IntegerField(verbose_name='Диаметр колес')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('price', models.CharField(default='Договорнаяя', max_length=100, verbose_name='Цена (BYN)')),
                ('type_of_ram', models.BooleanField(blank=True, verbose_name='Складная рама')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
