# Generated by Django 3.2.8 on 2021-10-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byke',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/'),
        ),
    ]
